### ISSUE TITLE
Profile invariants constraining meta.profile not working - need to be relative not absolute 

### ISSUE THREAD

**Issue by dtr-agency** [AuDigitalHealth/ci-fhir-stu3#39]
# Prerequisites

- [X] I have verified the problem exists in the available content
- [X] I have searched [open](https://github.com/ci-fhir-stu3/Issues/issues) and [closed](https://github.com/ci-fhir-stu3/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title

# The bug
In some profiles a conformance points is that the profile shall declare itself conformant, this is done via an invariant on the meta element of the applicable resource e.g. Composition.meta, to fix the value of one instance of meta.profile.uri to be the uri of that profile. 

The FHIRPath is written with an absolute path (i.e. includes the root resource element), e.g.:

> Composition.meta.profile.where($this = 'http://ns.electronichealth.net.au/ci/fhir/3.0/StructureDefinition/composition-shs-1').exists()

When building an IG the QA report coming out of IG Publisher generates an error for any example claiming conformance to one of these profiles with this type of rule declaring that the rule isn't satisifed. In other words a Composition example claiming conformance to 'http://ns.electronichealth.net.au/ci/fhir/3.0/StructureDefinition/composition-shs-1' by including a that value in the Composition.meta.profile.uri.value will generate an error that Composition.meta.profile.uri.value is missing the value.  

Clearly it is not missing the value, so the issue is with the invariant - on build generates errors that the composition does not include the meta.profile uri for which it claims conformance, e.g. if a composition claims to be conformant to 'http://ns.electronichealth.net.au/ci/fhir/3.0/StructureDefinition/composition-shs-1' which requires that meta.profile.uri value then an error that the meta.profile.uri is missing is generated in the QA.html.

Changing the FHIRPath of the invariant in the profile to a relative path eliminates the error, e.g.:

> profile.where($this='http://ns.electronichealth.net.au/ci/fhir/3.0/StructureDefinition/composition-shs-1').exists()

The FHIRPath of the invariants on meta to fix an instance of meta.profile.uri.value need to be changed from absolute path to relative path in the following profiles:
- composition-shs-1 (Shared Health Summary)
- composition-acp-1 (Advance Care Planning)
- composition-es-1 (Event Summary)
- composition-phn-1 (Personal Health Notes)
- composition-phs-1 (Personal Health Summary)
- composition-sml-1 (Shared Medicines List)
- documentreference-acp-1 (Advance Care Planning Document Reference)
- list-meditems-1 (List of Medicine Items for a Patient)

## What I expected to happen
On build of the FHIR-IGs in this repository none of the generated QA error reports includes an error 'One meta.profile shall be ...'

## Steps to reproduce
1. Build one of the FHIR-IGs (it must have examples included)
2. View the QA report, e.g. '..//git/ci-fhir-stu3/output/EventSummary/qa.html'
3. Scroll down to the error report for a bundle example e.g. ..\\git\ci-fhir-stu3\examples\bundle-7fdbd082-b9c4-46bf-ac8d-8f71de24ac4a.xml
4. Confirm there is no instance of the error 'One meta.profile shall be ...'
5. Confirm that the bundle example actually conforms to the required profile by including a value in meta.profile.uri as required by the applicable profile in the implementation guide

## Workarounds
N/A

## QA.html excerpt
The QA.html report for Shared Health Summary FHIR IG outputs this error for 8 example instances (there are 8 examples with a composition claiming conformance to composition-shs-1):

> One meta.profile shall be 'http://ns.electronichealth.net.au/ci/fhir/3.0/StructureDefinition/composition-shs-1' [Composition.meta.profile.where($this = 'http://ns.electronichealth.net.au/ci/fhir/3.0/StructureDefinition/composition-shs-1').exists()]

## Desktop (please complete the following information):
- OS: Windows 10
- Google Chrome
- 28 May 2019
